<?php

use Drupal\Core\Url;

/**
 * @param array $page_top
 */

function monsido_page_top(array &$page_top) {
    
    $current_url = \Drupal::request()->getRequestUri();
    
    if(strstr($current_url, '/edit')){
        
        $node = \Drupal::routeMatch()->getParameter('node');
        $nid = $node->id();
        $options = ['absolute' => true];
        $url = \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => $nid], $options);
        $url = $url->toString();

        $page_top['monsido'] = [
            '#type' => 'inline_template',
            '#template' => "<!-- Monsido: public_urls['{$url}'] -->"
        ];
    }
}
